server:
  port: 8083

spring:
  application:
    name: admin-server
  security:
    user:
      name: admin
      password: adminpassword

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
