spring.application.name=inventory-service
server.port=8082
server.shutdown=graceful

# Database
spring.datasource.url=${DB_URL_INVENTORY}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.hibernate.ddl-auto=update

# Security logging
logging.level.org.springframework.security=debug

# JWT Security
jwt.secret=${JWT_SECRET:SmartServSuperSecretKeyForJWTTokenGeneration2026MustBeAtLeast32BytesLongSecretKey!}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
